### ISSUE TITLE
Linting crashes while loading rule `unicorn/filename-case`

### ISSUE THREAD

**Issue by pustovitDmytro** [sindresorhus/eslint-plugin-unicorn#1511]
I use eslint-plugin-unicorn on my public [repository](https://github.com/pustovitDmytro/semantic-release-telegram). After upgrade to [v35](https://github.com/pustovitDmytro/semantic-release-telegram/pull/45),  the next [error](https://scrutinizer-ci.com/g/pustovitDmytro/semantic-release-telegram/inspections/d35a079e-69cf-4231-a394-d4a22fc9e649) is shown on running elint:

```
Oops! Something went wrong! :(

ESLint: 7.26.0

TypeError: Error while loading rule 'unicorn/filename-case': context.getPhysicalFilename is not a function
Occurred while linting /home/dima/Projects/pet/semantic-release-telegram/src/Error.js
    at create (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint-plugin-unicorn/rules/filename-case.js:156:40)
    at Object.wrapped [as create] (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:38:18)
    at createRuleListeners (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:761:21)
    at /home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:931:31
    at Array.forEach (<anonymous>)
    at runRules (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:876:34)
    at Linter._verifyWithoutProcessors (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:1175:31)
    at Linter._verifyWithConfigArray (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:1273:21)
    at Linter.verify (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:1228:25)
    at Linter.verifyAndFix (/home/dima/Projects/pet/semantic-release-telegram/node_modules/eslint/lib/linter/linter.js:1418:29)
```

[File, that causes failure ](https://github.com/pustovitDmytro/semantic-release-telegram/blob/master/src/Error.js)

**Comment by sindresorhus** [comment]
You need to upgrade your ESLint version.
