### ISSUE TITLE
Token "items" does not exist.

### ISSUE THREAD

**Issue by Shinigami92** [sindresorhus/eslint-plugin-unicorn#1575]
While generating definitions for unicorn in `eslint-define-config` I get two errors related to unicorn.

Hopefully this helps and you can fix the schema.

- `import-style`
- `prevent-abbreviations`

```
Failed to generate rule 'import-style' for Unicorn.
 MissingPointerError: Token "items" does not exist.
    at Pointer.resolve (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)
    at $Ref.resolve (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:124:20)
    at $Refs._resolve (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)
    at dereference$Ref (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:133:23)
    at crawl (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:62:28)
    at crawl (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)
    at dereference (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:19:22)
    at $RefParser.dereference (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:269:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 

Failed to generate rule 'prevent-abbreviations' for Unicorn.
 MissingPointerError: Token "items" does not exist.
    at Pointer.resolve (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js:94:13)
    at $Ref.resolve (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js:124:20)
    at $Refs._resolve (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js:156:15)
    at dereference$Ref (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:133:23)
    at crawl (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:62:28)
    at crawl (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:71:30)
    at dereference (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/dereference.js:19:22)
    at $RefParser.dereference (/home/shinigami/OpenSource/Shinigami92/eslint-define-config/node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/index.js:269:5)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by fisker** [comment]
@Shinigami I went to eslint-define-config and ran `pnpm generate unicorn/import-style` didn't see an error, don't know how to test, but please check #1582

**Comment by Shinigami92** [comment]
I think this will solve my issue, cause in the new generated schema there is `items`

**Comment by fisker** [comment]
> in the new generated schema there is items

I don't think it's caused by `items`, but `$ref`

**Comment by Shinigami92** [comment]
@fisker I can confirm that it works 👍

**Comment by fisker** [comment]
Great, thanks.
