### ISSUE TITLE
Updating to `44.0.0` cause a `TypeError`

### ISSUE THREAD

**Issue by zloirock** [sindresorhus/eslint-plugin-unicorn#1923]
After updating to `44.0.0`, I have:
```
> eslint ./

Oops! Something went wrong! :(

ESLint: 8.24.0

TypeError: Cannot read properties of undefined (reading 'replace')
    at /###/core-js/node_modules/eslint/lib/cli-engine/formatters/stylish.js:68:37
    at Array.map (<anonymous>)
    at /###/core-js/node_modules/eslint/lib/cli-engine/formatters/stylish.js:53:22
    at Array.forEach (<anonymous>)
    at module.exports (/###/core-js/node_modules/eslint/lib/cli-engine/formatters/stylish.js:38:13)
    at Object.format (/###/core-js/node_modules/eslint/lib/eslint/flat-eslint.js:1124:24)
    at printResults (/###/core-js/node_modules/eslint/lib/cli.js:255:36)
    at async Object.execute (/###/core-js/node_modules/eslint/lib/cli.js:410:13)
    at async main (/###/core-js/node_modules/eslint/bin/eslint.js:135:24)
```

`43.0.2` works fine.

MacOS `12.6`, NodeJS `18.10`, ESLint `8.24.0`, flat config.

[ESlint config and the code base.](https://github.com/zloirock/core-js/blob/afcc1481cd8418ece936e214a2ebc701ab322ed9/eslint.config.js)

**Comment by fisker** [comment]
`npm i` taking forever...

**Comment by fisker** [comment]
Located.
