### ISSUE TITLE
unicorn/expiring-todo-comments fails with eslint 8.40.0

### ISSUE THREAD

**Issue by AlexAegis** [sindresorhus/eslint-plugin-unicorn#2076]
Environment:

node: 20.1.0
pnpm: 8.4.0
eslint: 8.40.0
eslint-plugin-unicorn: 46.0.0

Running eslint gives me this error for `unicorn/expiring-todo-comments`:

```sh
TypeError: Cannot read properties of undefined (reading 'getAllComments')
Occurred while linting /home/alex/git/@aa/js-core/packages/common/.eslintrc.cjs:4
Rule: "unicorn/expiring-todo-comments"
    at Object.Program (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
    at Program (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint-plugin-unicorn@46.0.0_eslint@8.40.0/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:514:10)
    at /home/alex/git/@aa/js-core/node_modules/.pnpm/eslint-plugin-unicorn@46.0.0_eslint@8.40.0/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
    at ruleErrorHandler (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/linter.js:1049:28)
    at /home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/home/alex/git/@aa/js-core/node_modules/.pnpm/eslint@8.40.0/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
 ELIFECYCLE  Command failed with exit code 2.
```

This is the last place the trace mentions: `rules/no-warning-comments.js:193:45`

![image](https://user-images.githubusercontent.com/16900547/236576972-6ef414d9-927e-4cef-8087-28d43e45ccf0.png)

If I turn this rule off, then eslint finishes just fine.

```js
/** @type {import('eslint').Linter.Config} */
module.exports = {
	root: true,
	extends: ['@alexaegis/eslint-config-core'],
	rules: {
		'unicorn/expiring-todo-comments': 'off',
	},
};
```

**Comment by AlexAegis** [comment]
Ironically that temporary rule override would be a perfect place to add an expiring todo.

**Comment by seanblonien** [comment]
same error for me too -- do we have a minimal repro steps for this? 

curious to know if these tests are all still passing: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/test/expiring-todo-comments.mjs

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v46.0.1
