### ISSUE TITLE
Crashes linter when unicorn/expiring-todo-comments

### ISSUE THREAD

**Issue by drFabio** [sindresorhus/eslint-plugin-unicorn#2117]
My whole linter was not working, not on vs code not anywhere. Disabling this rule made it work

unicorn/expiring-todo-comments"

```ts
/* eslint-disable node/no-process-env*/
import { resolve as pathResolve } from 'node:path';
import { producerStackFactory } from 'warehouse-lambda/utils';
import { APP_NAME, outboundInterfaces } from '../lib/constants';

producerStackFactory(APP_NAME, outboundInterfaces, {
  functionProps: {
    entry: pathResolve(__dirname, '../lib/handler.ts'),
  },
});
```

Whole error:

```
TypeError: Cannot read properties of undefined (reading 'getAllComments')
Occurred while linting /some-project/apps/dhl-outbound-reader/src/bin/dhl-outbound-reader.app.ts:2
Rule: "unicorn/expiring-todo-comments"
    at Object.Program (/some-project/node_modules/eslint/lib/rules/no-warning-comments.js:193:45)
    at Program (/some-project/node_modules/eslint-plugin-unicorn/rules/expiring-todo-comments.js:511:10)
    at /some-project/node_modules/eslint-plugin-unicorn/rules/utils/rule.js:39:18
    at ruleErrorHandler (/some-project/node_modules/eslint/lib/linter/linter.js:1049:28)
    at /some-project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/some-project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/some-project/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/some-project/node_modules/eslint/lib/linter/node-event-generator.js:326:22)
    at NodeEventGenerator.enterNode (/some-project/node_modules/eslint/lib/linter/node-event-generator.js:340:14)
```

**Comment by sindresorhus** [comment]
This was already fixed: https://github.com/sindresorhus/eslint-plugin-unicorn/releases/tag/v46.0.1
