### ISSUE TITLE
plugin:unicorn/recommended: Environment key "es2024" is unknown

### ISSUE THREAD

**Issue by ferferga** [sindresorhus/eslint-plugin-unicorn#2204]
### Description
When enabling the ``no-unused-keys`` from the [eslint-plugin-vue-i18n](https://github.com/intlify/eslint-plugin-vue-i18n) project, I get this error. As soon as I remove ``plugin:unicorn/recommended`` from the ``extends`` section, it works without issues. This looks similar to #1741 but all my deps are up to date.

### Versions
```
eslint: 8.52.0
eslint-plugin-unicorn: 48.0.1
@intlify/eslint-plugin-vue-i18n: 2.0.0
```

### Traceback
```
Oops! Something went wrong! :(

ESLint: 8.52.0

Error: Error while loading rule '@intlify/vue-i18n/no-unused-keys': .eslintrc.cjs » plugin:unicorn/recommended:
        Environment key "es2024" is unknown

Occurred while linting /workspaces/jellyfin-vue/frontend/locales/ar.json
    at /workspaces/jellyfin-vue/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2058:23
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateEnvironment (/workspaces/jellyfin-vue/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2052:34)
    at ConfigValidator.validateConfigArray (/workspaces/jellyfin-vue/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:2202:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (/workspaces/jellyfin-vue/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3962:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/workspaces/jellyfin-vue/node_modules/@eslint/eslintrc/dist/eslintrc.cjs:3768:21)
    at getConfigForFile (/workspaces/jellyfin-vue/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/collect-keys.js:121:14)
    at collectKeysFromText (/workspaces/jellyfin-vue/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/collect-keys.js:73:20)
    at ResourceLoader.loader (/workspaces/jellyfin-vue/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/collect-keys.js:114:20)
    at ResourceLoader.getResource (/workspaces/jellyfin-vue/node_modules/@intlify/eslint-plugin-vue-i18n/dist/utils/resource-loader.js:32:39)
```

### How to reproduce

1. Open [this PR](https://github.com/jellyfin/jellyfin-vue/pull/1985)
2. Click on Code > Create codespace.
3. Once the codespace is loaded, run ``npm run lint``. It will not work and the same traceback as above will be displayed
5. Comment line 205 (at the time of writing) to disable the ``no-unused-keys`` rule. Linter will keep running.
6. Uncomment that line and comment line 46 (at the time of writing) to disable ``plugin:unicorn/recommended``

**Comment by Yvad60** [comment]
Facing the same issue on ESLint: 8.38.0

**Comment by dimaMachina** [comment]
You just need to follow package peerDependency requirements https://github.com/sindresorhus/eslint-plugin-unicorn/blob/61e66017f0c582c8a2537ca23b2e858e1fad8908/package.json#L96

**Comment by ferferga** [comment]
@dimaMachina But I'm using eslint 8.52.0 (which is the latest version as well)

**Comment by fisker** [comment]
Since it's actually from `@eslint/eslintrc`, please make sure it's updated as well.

**Comment by fisker** [comment]
https://github.com/eslint/eslintrc/blob/3b386f790119553fb0d800b65454abf89b56a7aa/conf/environments.js#L123
