### ISSUE TITLE
Key "plugins": Cannot redefine plugin "unicorn"

### ISSUE THREAD

**Issue by rafipiccolo** [sindresorhus/eslint-plugin-unicorn#2325]
I'm transitionning from eslint 8 to 9.

in eslint 9 there is not one rule in particular that fails. I just cant run eslint

.eslintrc
```js
{
    "plugins": ["unicorn"],
    "extends": [ "eslint:recommended", "plugin:unicorn/recommended" ] 
    "parser": "@babel/eslint-parser",
    "parserOptions": {
        "ecmaVersion": "latest",
        "sourceType": "module",
        "requireConfigFile": false
    }
}
```
to
eslint.config.js
```js
import js from "@eslint/js";
import unicorn from "eslint-plugin-unicorn";

export default [
    // activate this line to get error
    // before it was named : "eslint:recommended"
    // --------
    // js.configs.recommended, 

    unicorn.configs['flat/recommended'],
    {
        files: ["**/*.js"],
        languageOptions: {
            parser: babelParser,
            parserOptions: {
                ecmaVersion: "latest",
                sourceType: "module",
                requireConfigFile: false,
            },
        },
        plugins: {
            unicorn,
        }
    }
}
```

```bash
eslint server.js 

Oops! Something went wrong! :(

ESLint: 9.2.0

ConfigError: Config (unnamed): Key "plugins": Cannot redefine plugin "unicorn".
    at rethrowConfigError (/usr/local/lib/node_modules/eslint/node_modules/@humanwhocodes/config-array/api.js:230:8)
    at /usr/local/lib/node_modules/eslint/node_modules/@humanwhocodes/config-array/api.js:1032:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfig (/usr/local/lib/node_modules/eslint/node_modules/@humanwhocodes/config-array/api.js:1028:39)
    at FlatConfigArray.isFileIgnored (/usr/local/lib/node_modules/eslint/node_modules/@humanwhocodes/config-array/api.js:1060:15)
    at /usr/local/lib/node_modules/eslint/lib/eslint/eslint-helpers.js:548:38
    at Array.forEach (<anonymous>)
    at findFiles (/usr/local/lib/node_modules/eslint/lib/eslint/eslint-helpers.js:537:11)
    at async ESLint.lintFiles (/usr/local/lib/node_modules/eslint/lib/eslint/eslint.js:847:27)
    at async Object.execute (/usr/local/lib/node_modules/eslint/lib/cli.js:500:23)
```

i tried setting

**Comment by rafipiccolo** [comment]
ok my bad, i needed to remove this part
```
plugins: {
            unicorn,
        }
```

I guess the extends now does it itself

**Comment by fisker** [comment]
`unicorn.configs['flat/recommended']` enables "unicorn" plugin

**Comment by zzzgit** [comment]
> `unicorn.configs['flat/recommended']` enables "unicorn" plugin

why not write it in the document so that everyone can know it.
