### ISSUE TITLE
Remove bad fix for `no-for-loop`

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#2424]
```
  no-for-loop › invalid(1): for (let i = 0; i < positions.length; i++) { \u0009let last: vscode.Position | vscode.Range = positions[i]; \u0009let selectionRange = allProviderRanges[i]; }

  Assertion failed: 

  A fatal parsing error occurred in autofix.
  Error: Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  Autofix output:
  for (let [i, last]: [number, vscode.Position | vscode.Range] of positions.entries()) {
  	let selectionRange = allProviderRanges[i];
  }

  AssertionError [ERR_ASSERTION]: A fatal parsing error occurred in autofix.
  Error: Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  Autofix output:
  for (let [i, last]: [number, vscode.Position | vscode.Range] of positions.entries()) {
  	let selectionRange = allProviderRanges[i];
  }
      at runRuleForItem (/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:828:17)
      at testInvalidTemplate (/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:967:28)
      at /home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:1274:33
      at file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint-ava-rule-tester/index.js:27:7
      at Test.callFn (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/test.js:525:26)
      at Test.run (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/test.js:534:33)
      at Runner.runSingle (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/runner.js:281:33)
      at Runner.runTest (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/runner.js:363:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 92)



  no-for-loop › invalid(2): for (let i = 0; i < positions.length; i++) { \u0009const last /* comment */ : /* comment */ Position = positions[i]; \u0009console.log(i); }

  Assertion failed: 

  A fatal parsing error occurred in autofix.
  Error: Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  Autofix output:
  for (const [i, last   /* comment */]: [number, /* comment */ Position] of positions.entries()) {
  	console.log(i);
  }

  AssertionError [ERR_ASSERTION]: A fatal parsing error occurred in autofix.
  Error: Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  Autofix output:
  for (const [i, last   /* comment */]: [number, /* comment */ Position] of positions.entries()) {
  	console.log(i);
  }
      at runRuleForItem (/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:828:17)
      at testInvalidTemplate (/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:967:28)
      at /home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:1274:33
      at file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint-ava-rule-tester/index.js:27:7
      at Test.callFn (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/test.js:525:26)
      at Test.run (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/test.js:534:33)
      at Runner.runSingle (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/runner.js:281:33)
      at Runner.runTest (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/runner.js:363:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 93)



  no-for-loop › invalid(3): for (let i = 0; i < positions.length; i++) { \u0009let last: vscode.Position | vscode.Range = positions[i]; }

  Assertion failed: 

  A fatal parsing error occurred in autofix.
  Error: Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  Autofix output:
  for (let last: vscode.Position | vscode.Range of positions) {
  }

  AssertionError [ERR_ASSERTION]: A fatal parsing error occurred in autofix.
  Error: Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  Autofix output:
  for (let last: vscode.Position | vscode.Range of positions) {
  }
      at runRuleForItem (/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:828:17)
      at testInvalidTemplate (/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:967:28)
      at /home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint/lib/rule-tester/rule-tester.js:1274:33
      at file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/eslint-ava-rule-tester/index.js:27:7
      at Test.callFn (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/test.js:525:26)
      at Test.run (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/test.js:534:33)
      at Runner.runSingle (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/runner.js:281:33)
      at Runner.runTest (file:///home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/node_modules/ava/lib/runner.js:363:30)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Promise.all (index 94)

  ─

  3 tests failed
```

_Originally posted by @axetroy in https://github.com/sindresorhus/eslint-plugin-unicorn/issues/2410#issuecomment-2290700176_

Root cause https://github.com/sindresorhus/eslint-plugin-unicorn/blob/5c92a9aed7793afa00f23e72e25bc58c10adecd4/rules/no-for-loop.js#L381

**Comment by axetroy** [comment]
Not only that, here is another one.

The reason is that vscode uses a new syntax, but the plugin did not updated the parser

```
> eslint-plugin-unicorn@55.0.0 integration
> node ./test/integration/test.mjs --group 9

[07:42:24] vscode [started]
[07:42:24] vscode / Cloning [started]
Cloning into '/home/runner/work/eslint-plugin-unicorn/eslint-plugin-unicorn/test/integration/fixtures/vscode'...
[07:42:29] vscode / Cloning [completed]
[07:42:29] vscode / Running eslint [started]
(node:1825) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files
(Use `node --trace-warnings ...` to show where the warning was created)
[07:49:43] vscode / Running eslint [failed]
[07:49:43] → Error thrown when linting 'vscode' project.
[07:49:43] vscode [failed]

[vscode] Error thrown when linting 'vscode' project.

https://github.com/microsoft/vscode/blob/main/src/vs/workbench/api/common/extHostLanguageFeatures.ts#L1894

  1892 | 		}
  1893 | 		const allResults: languages.SelectionRange[][] = [];
> 1894 | 		for (let [i, last]: [number, vscode.Position | vscode.Range] of positions.entries()) {
       | 		        ^ Parsing error: The variable declaration of a 'for...of' statement cannot have a type annotation.
  1895 | 			const oneResult: languages.SelectionRange[] = [];
  1896 | 			allResults.push(oneResult);
  1897 |
Rule                             | Time (ms) | Relative
:--------------------------------|----------:|--------:
unicorn/prevent-abbreviations    | 13999.394 |     6.6%
unicorn/no-thenable              | 13673.376 |     6.4%
unicorn/no-keyword-prefix        | 11337.131 |     5.3%
unicorn/better-regex             | 11123.204 |     5.2%
unicorn/expiring-todo-comments   |  7078.550 |     3.3%
unicorn/prefer-array-flat        |  6285.208 |     3.0%
unicorn/no-unnecessary-polyfills |  5806.315 |     2.7%
unicorn/prefer-spread            |  5735.739 |     2.7%
unicorn/prefer-array-find        |  5127.295 |     2.4%
unicorn/no-array-for-each        |  4888.975 |     2.3%
```
