### ISSUE TITLE
Webstorm cannot find plugin as a part of .eslintrc

### ISSUE THREAD

**Issue by ViktorSoroka07** [sindresorhus/eslint-plugin-unicorn#249]
package.json
```
"devDependencies": {
    "eslint": "^5.14.1",
    "eslint-plugin-unicorn": "^7.1.0"
}
```
.eslintrc
```
{
  "globals": {
    "process": true
  },
  "plugins": ["unicorn"],
  "root": true,
  "rules": {
    "unicorn/catch-error-name": "error"
  }
}
```

And eventually get an error:

```
Error: Failed to load plugin unicorn: Cannot find module 'eslint-plugin-unicorn'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.resolve (internal/modules/cjs/helpers.js:30:19)
    at Plugins.load (<path>/node_modules/eslint/lib/config/plugins.js:104:29)
    at Array.forEach (<anonymous>)
    at Plugins.loadAll (<path>/node_modules/eslint/lib/config/plugins.js:165:21)
    at loadFromDisk (<path>/node_modules/eslint/lib/config/config-file.js:506:35)
    at Object.load (<path>/node_modules/eslint/lib/config/config-file.js:564:20)
    at Config.getLocalConfigHierarchy (<path>/node_modules/eslint/lib/config.js:240:44)
    at Config.getConfigHierarchy (<path>/node_modules/eslint/lib/config.js:192:43)
    at Config.getConfigVector (<path>/node_modules/eslint/lib/config.js:299:21)
```

**Comment by fregante** [comment]
This isn't unlikely to be a `eslint-plugin-unicorn` issue. Check your WebStorm configuration and make sure that `eslint-plugin-unicorn` is installed where it expects it to be (locally or globally?)

Examples:

- https://intellij-support.jetbrains.com/hc/en-us/community/posts/207372315-Inspections-failing-with-Error-Cannot-find-module-eslint-config-standard-
- https://intellij-support.jetbrains.com/hc/en-us/community/posts/360007972280-Error-Failed-to-load-plugin-prettier-Cannot-find-module-eslint-plugin-prettier-
