### ISSUE TITLE
`no-for-loop` rule bug with `@typescript-eslint/parser`

### ISSUE THREAD

**Issue by SimonSiefke** [sindresorhus/eslint-plugin-unicorn#272]
I'm runnning into an issue with the `no-for-loop` rule. Here is the code:
```javascript
const links = document.querySelectorAll('link')
for (let i = 0; i < links.length; i++) {
  const link = links[i]
}
```

The ESLint config:
```javascript
module.exports = {
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', 'unicorn'],
  rules: {
    'unicorn/no-for-loop': 'error',
  },
}
```
However, it is working fine without `@typescript-eslint/parser`.

And here is the stacktrace from VSCode:
```
[Error - 11:07:51 PM] ESLint stack trace:
[Error - 11:07:51 PM] TypeError: Expected `index` to be a number.
Occurred while linting /home/simon/Documents/self-tuts/live-server/unicorn.bug.js:2
    at SourceCode.getLocFromIndex (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/source-code.js:436:19)
    at getRemovalRange (/home/simon/Documents/self-tuts/live-server/node_modules/eslint-plugin-unicorn/rules/no-for-loop.js:171:28)
    at Object.ForStatement.problem.fix.fixer [as fix] (/home/simon/Documents/self-tuts/live-server/node_modules/eslint-plugin-unicorn/rules/no-for-loop.js:308:25)
    at normalizeFixes (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/report-translator.js:176:28)
    at args (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/report-translator.js:278:18)
    at Object.report (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/linter.js:721:41)
    at ForStatement (/home/simon/Documents/self-tuts/live-server/node_modules/eslint-plugin-unicorn/rules/no-for-loop.js:313:12)
    at listeners.(anonymous function).forEach.listener (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/home/simon/Documents/self-tuts/live-server/node_modules/eslint/lib/util/safe-emitter.js:45:38)
```

**Comment by SimonSiefke** [comment]
I have created https://github.com/typescript-eslint/typescript-eslint/issues/392
