### ISSUE TITLE
prefer-flat-map: "Fix objects must not be overlapped in a report."

### ISSUE THREAD

**Issue by borekb** [sindresorhus/eslint-plugin-unicorn#316]
My config:

```js
module.exports = {
  parser: '@typescript-eslint/parser',
  parserOptions: {
    ecmaVersion: 2018,
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  plugins: ['unicorn'],
  rules: {
    'unicorn/prefer-flat-map': 'error',
  },
};
```

It runs fine on one sub-project in our repo:

```
yarn eslint -f stylish "project-1/**/*.ts"
```

But fails on another subfolder:

```
$ yarn eslint -f stylish "project-2/**/*.ts"

AssertionError [ERR_ASSERTION]: Fix objects must not be overlapped in a report.
    at mergeFixes (/Users/borekb/example/node_modules/eslint/lib/util/report-translator.js:150:9)
    at normalizeFixes (/Users/borekb/example/node_modules/eslint/lib/util/report-translator.js:180:16)
    at args (/Users/borekb/example/node_modules/eslint/lib/util/report-translator.js:278:18)
    at Object.report (/Users/borekb/example/node_modules/eslint/lib/linter.js:720:41)
    at report (/Users/borekb/example/node_modules/eslint-plugin-unicorn/rules/prefer-flat-map.js:60:10)
    at CallExpression (/Users/borekb/example/node_modules/eslint-plugin-unicorn/rules/prefer-flat-map.js:107:3)
    at listeners.(anonymous function).forEach.listener (/Users/borekb/example/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/borekb/example/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/borekb/example/node_modules/eslint/lib/util/node-event-generator.js:251:26)
```

I could try to narrow it down but there's quite a bit of files in `project-2` so maybe someone already knows what this could be?

A few observations:

- Only `prefer-flat-map` causes this; I tried running all the other rules on our entire codebase and all was fine.
- It might be related to TypeScript but I'm not sure as we don't have many `*.js` files in our repo.

**Comment by MrHen** [comment]
I know what the error means but not what causes it. Can you post a couple examples of where you use shapes similar to `.map().flat()`?

**Comment by borekb** [comment]
There's actually a single instance of `.flat()` in our codebase, and it's called on an array returned from Apollo Client:

```ts
const cartItemsWithVariants: CartItem[] = filteredProducts
      .filter(product => !!product.variants)
      .map(product => transformProduct(product))
      .flat();
```

Cmd+click on `flat` brings me to `node_modules/apollo-env/src/polyfills/array.ts` that looks like this:

```ts
import "core-js/features/array/flat";
import "core-js/features/array/flat-map";

declare global {
  interface Array<T> {
    flat<U>(this: ReadonlyArray<U>[], depth?: 1): U[];
    flatMap<U>(
      callbackfn: (value: T, index: number, array: T[]) => ReadonlyArray<U> | U,
      thisArg?: this
    ): U[];
  }
}
```

I'm not too familiar with this piece of code so hopefully, it provides at least some hints.

**Comment by MrHen** [comment]
Thanks for the example! I'll dig into what could be causing it and let you know what I find.

**Comment by borekb** [comment]
No problem, thanks so much for looking into it so swiftly!

Just as a note, when I updated the code to use `.flatMap`, the issue went away.

**Comment by MrHen** [comment]
I was able to reproduce this bug. It is TypeScript specific. When I add your example scenario in a JavaScript context, the lint rule worked as expected. When I set everything up using TypeScript, I saw the "Fix objects must not be overlapped in a report." output.
