### ISSUE TITLE
prefer-starts-ends-with crashes

### ISSUE THREAD

**Issue by dikmax** [sindresorhus/eslint-plugin-unicorn#81]
I've tried new rule from `eslint-plugin-unicorn`, but it crashes.

```
Cannot read property 'name' of undefined
TypeError: Cannot read property 'name' of undefined
    at EventEmitter.CallExpression (/Users/dikmax/workspace/project/app/node_modules/eslint-plugin-unicorn/rules/prefer-starts-ends-with.js:16:23)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Users/dikmax/workspace/project/app/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/dikmax/workspace/project/app/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
    at Controller.Traverser.controller.traverse (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/util/traverser.js:36:33)
```

[Link to line with error](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/rules/prefer-starts-ends-with.js#L16)

It could be because of babel-eslint parser. But anyway rule should not crash.

**Comment by sindresorhus** [comment]
Can you share the line of your code (or something similar) that reproduces the crash?

**Comment by dikmax** [comment]
I've debugged a little and found out that it crashes on this code.

```js
export function upsert(collection: Mongo.Collection,
                       result: Array<Object>): Promise<void> {
    return result.reduce(
        (prev: Promise<void>, current: Object): Promise<void> =>
            prev.then(() =>
                new Promise((resolve: () => void, reject: (err: any) => void) => {
                    collection.update({
                        _id: current._id
                    }, current, {upsert: true}, (err: any) => {
                        if (err) {
                            reject(err);
                            return;
                        }
                        resolve();
                    });
                })
            ),
        Promise.resolve() // Initial resolved
    );
}
```

Exacly on `reject(err)` statement.

**Comment by SamVerschueren** [comment]
It has to check `if (callee.property)` as well because `reject(new Error('foo'))` is a `CallExpression` where the `callee` property doesn't have a `property` property.

**Comment by sindresorhus** [comment]
I'm working on a fix.

**Comment by sindresorhus** [comment]
@dikmax Sorry about the issues. I've opened https://github.com/sindresorhus/eslint-plugin-unicorn/issues/84 to make it a lot less likely we ship crashing issues in the future.

**Comment by sindresorhus** [comment]
2.0.1 published

**Comment by dikmax** [comment]
Cool! Thanks a lot!
