### ISSUE TITLE
prefer-type-error crashes

### ISSUE THREAD

**Issue by dikmax** [sindresorhus/eslint-plugin-unicorn#82]
One more crash with new rules from unicorn.

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at node (/Users/dikmax/workspace/project/app/node_modules/eslint-plugin-unicorn/rules/prefer-type-error.js:64:18)
    at EventEmitter.ThrowStatement.context.report (/Users/dikmax/workspace/project/app/node_modules/eslint-plugin-unicorn/rules/prefer-type-error.js:108:5)
    at emitOne (events.js:82:20)
    at EventEmitter.emit (events.js:169:7)
    at NodeEventGenerator.enterNode (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/util/node-event-generator.js:39:22)
    at CodePathAnalyzer.enterNode (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/code-path-analysis/code-path-analyzer.js:607:23)
    at CommentEventGenerator.enterNode (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/util/comment-event-generator.js:98:23)
    at Controller.enter (/Users/dikmax/workspace/project/app/node_modules/eslint/lib/eslint.js:928:36)
    at Controller.__execute (/Users/dikmax/workspace/project/app/node_modules/eslint/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/dikmax/workspace/project/app/node_modules/eslint/node_modules/estraverse/estraverse.js:501:28)
```

[Link to line with error](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/rules/prefer-type-error.js#L64)

Probably you should check for `undefined` instead of `null`.

**Comment by sindresorhus** [comment]
Can you provide something that reproduces it? We need to that so we can make regression tests.

// @florianb

**Comment by dikmax** [comment]
```js
switch (something) {
  case 1:
    break;
  default:
    throw new Error('Unknown');
}
```
