### ISSUE TITLE
`error-message`: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by fisker** [sindresorhus/eslint-plugin-unicorn#915]
When running on this code,

```js
const a = undefined;
function b() {
  throw undefined;
}
```

```text
RangeError: Maximum call stack size exceeded
Occurred while linting <CWD>\1.ts:1
    at findIdentifierValues (<CWD>\rules\error-message.js:32:24)
    at checkErrorMessage (<CWD>\rules\error-message.js:80:28)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4)
    at checkErrorMessage (<CWD>\rules\error-message.js:82:4) {
  currentNode: Node {
    type: 'Program',
    start: 0,
    end: 58,
    loc: SourceLocation { start: [Position], end: [Position] },
    range: [ 0, 57 ],
    body: [ [Node], [Node], [Node] ],
    sourceType: 'module',
    comments: [],
    tokens: [
      [Token], [Token], [Token],
      [Token], [Token], [Token],
      [Token], [Token], [Token],
      [Token], [Token], [Token],
      [Token], [Token], [Token]
    ],
    parent: null
  }
}
```

This is not a real-world code, but I don't know what's wrong yet.

Bug found during #914, file https://github.com/prettier/prettier/blob/master/tests/typescript/conformance/types/functions/functionImplementations.ts

**Comment by fisker** [comment]
``js
/* global x */
const a = x;
throw x;
```

This fails it too.

**Comment by fisker** [comment]
@sindresorhus This rule is a little hard for me to understand, it suppose check 

> Enforce passing a `message` value when throwing a built-in error

But the code tracking `ThrowStatement`, this make it hard to track the references, do you think we just check `NewExpression`? 


```js
const foo = new Error()
```

This should be a invalid case, even it didn't throw.

**Comment by sindresorhus** [comment]
> But the code tracking ThrowStatement, this make it hard to track the references, do you think we just check NewExpression?

That does sound like a better way to do it.

> This should be a invalid case, even it didn't throw.

👍🏻
